// Types + YAML serializer for the YAML creation UI. The schema JSON is
// regenerated by `pack.sh` from the vendored apworlds, so changes to
// upstream options.py are picked up the same way as ap.tar.

import yaml from "js-yaml";
import rawSchema from "../generated/yaml-schema.json";

export type OptionKind =
  | "toggle"
  | "toggle_on"
  | "choice"
  | "range"
  | "named_range"
  | "option_set"
  | "pokemon_set"
  | "option_dict"
  | "option_list"
  | "option_counter"
  | "free_text"
  | "other";

export type OptionDef = {
  name: string;             // Python class name, e.g. "EliteFourCount"
  yaml_key: string;         // dataclass field, e.g. "elite_four_count"
  kind: OptionKind;
  docstring: string;
  display_name: string;
  default: unknown;
  range_start?: number | null;
  range_end?: number | null;
  choices?: string[] | null;                          // "choice"
  special_range_names?: Record<string, number | null> | null;  // "named_range"
  valid_keys?: string[] | null;                       // "option_set"/"pokemon_set"
  valid_keys_computed?: boolean;
};

export type OptionGroup = { name: string; options: OptionDef[] };
export type WorldSchema = { game: string; groups: OptionGroup[] };

export type GameKey = "Pokemon Crystal" | "Pokemon Crystal Prerelease";

export const SCHEMAS: Record<GameKey, WorldSchema> = rawSchema as any;

// ---------------------------------------------------------------------------
// Form value model
//
// Each option in the form is either a single scalar value, or a weighted
// table when the user has toggled weights on for that option.
export type SingleValue = {
  mode: "single";
  value: string | number | boolean | string[];
};
export type WeightedValue = {
  mode: "weighted";
  // Each entry maps a serialized value (always a string) to an integer weight.
  // We keep these as parallel arrays rather than an object so the UI can
  // preserve insertion order while editing.
  entries: { value: string; weight: number }[];
};
export type FormValue = SingleValue | WeightedValue;

export type FormState = {
  game: GameKey;
  name: string;
  description: string;
  // yaml_key → FormValue. Options the user never touched are omitted and
  // serialize as the option's documented default.
  values: Record<string, FormValue>;
};

// ---------------------------------------------------------------------------
// YAML serialization
//
// Archipelago YAMLs are intentionally lenient — we don't need a full YAML
// emitter, just predictable output for the option types we drive. Strings
// that need quoting are wrapped in double quotes; everything else is emitted
// as a bare scalar / flow-style list / block mapping.

const NEEDS_QUOTING = /[:#\-\[\]\{\},&*!|>'%@`?]|^\s|\s$|^(true|false|null|yes|no|on|off|~)$/i;

function quoteIfNeeded(s: string): string {
  if (s === "") return '""';
  if (/^-?\d+(\.\d+)?$/.test(s)) return `"${s}"`;            // numeric-looking strings
  if (NEEDS_QUOTING.test(s)) return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  return s;
}

function emitScalar(v: unknown): string {
  if (v === true) return "true";
  if (v === false) return "false";
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  return quoteIfNeeded(String(v));
}

function emitFlowList(items: unknown[]): string {
  return "[" + items.map(emitScalar).join(", ") + "]";
}

function emitWeighted(entries: { value: string; weight: number }[]): string {
  // Inline mapping: { v1: w1, v2: w2 }
  const parts = entries
    .filter(e => e.value !== "" || e.weight > 0)
    .map(e => `${emitScalar(e.value)}: ${e.weight | 0}`);
  return "{" + parts.join(", ") + "}";
}

function defaultLiteral(opt: OptionDef): string {
  // For options the user never touched, emit a representation that matches
  // the option's documented default.
  const d = opt.default;
  if (opt.kind === "toggle" || opt.kind === "toggle_on") {
    // AP's YAML uses 0/1 weights here, but a bare scalar works too.
    return emitScalar(d === 1 || d === true);
  }
  if (opt.kind === "choice" && opt.choices && opt.choices.length) {
    // Choice options inherit AP's `default = 0` from NumericOption when they
    // don't declare one explicitly, so the schema may record `default: null`
    // (e.g. LockKantoGyms). Fall back to the first choice rather than emitting
    // an empty string, which fails generation with `Could not find option ""`.
    const idx = typeof d === "number" && opt.choices[d] !== undefined ? d : 0;
    return emitScalar(opt.choices[idx]);
  }
  if (opt.kind === "named_range" && opt.special_range_names) {
    for (const [name, val] of Object.entries(opt.special_range_names)) {
      if (val !== null && val === d) return emitScalar(name);
    }
    if (typeof d === "number") return emitScalar(d);
  }
  if (opt.kind === "range" && typeof d === "number") return emitScalar(d);
  if (Array.isArray(d)) return emitFlowList(d);
  if (d && typeof d === "object") {
    // option_dict / option_counter / etc. — emit as a flow-style mapping.
    try {
      return yaml.dump(d, { flowLevel: 0, lineWidth: -1 }).trim();
    } catch {
      return "{}";
    }
  }
  if (d === null || d === undefined) {
    // Sensible per-kind fallbacks.
    if (opt.kind === "range" && typeof opt.range_start === "number") return emitScalar(opt.range_start);
    if (opt.kind === "option_set" || opt.kind === "pokemon_set" || opt.kind === "option_list") return emitFlowList([]);
    // option_dict / option_counter / other — these are typically mapping-shaped
    // upstream (e.g. `start_inventory_from_pool` is an OptionDict). Emit an
    // empty mapping rather than a quoted empty string, which round-trips
    // through js-yaml without sprouting literal `''`.
    if (opt.kind === "option_dict" || opt.kind === "option_counter" || opt.kind === "other") return "{}";
    return '""';
  }
  return emitScalar(d);
}

function emitFormValue(opt: OptionDef, val: FormValue): string {
  if (val.mode === "weighted") return emitWeighted(val.entries);
  const v = val.value;
  if (opt.kind === "option_set" || opt.kind === "pokemon_set" || opt.kind === "option_list") {
    return emitFlowList(Array.isArray(v) ? v : []);
  }
  if (opt.kind === "toggle" || opt.kind === "toggle_on") return emitScalar(!!v);
  if (opt.kind === "option_dict" || opt.kind === "option_counter" || opt.kind === "other") {
    // The textarea holds inline YAML. Re-parse → re-emit as flow style so
    // it sits on one line next to the option key (no awkward block-style
    // indentation drift inside the rest of the document).
    const text = typeof v === "string" ? v.trim() : "";
    if (!text) return "{}";
    try {
      const parsed = yaml.load(text);
      if (parsed && typeof parsed === "object") {
        return yaml.dump(parsed, { flowLevel: 0, lineWidth: -1 }).trim();
      }
    } catch { /* fall through */ }
    return emitScalar(text);
  }
  return emitScalar(v);
}

const HEADER_TEMPLATE = `# Generated by Crystal AP Web — edit by hand if you want anything fancier.
# Docs: https://archipelago.gg/tutorial/Archipelago/setup/en
`;

export function serializeFormToYaml(form: FormState): string {
  const schema = SCHEMAS[form.game];
  const lines: string[] = [];
  lines.push(HEADER_TEMPLATE.trimEnd());
  lines.push("");
  lines.push(`name: ${emitScalar(form.name || "Player1")}`);
  if (form.description.trim()) lines.push(`description: ${emitScalar(form.description.trim())}`);
  lines.push(`game: ${emitScalar(schema.game)}`);
  lines.push("");
  lines.push(`${emitScalar(schema.game)}:`);

  for (const group of schema.groups) {
    lines.push("");
    lines.push(`  # --- ${group.name} ---`);
    for (const opt of group.options) {
      const user = form.values[opt.yaml_key];
      const rendered = user ? emitFormValue(opt, user) : defaultLiteral(opt);
      lines.push(`  ${opt.yaml_key}: ${rendered}`);
    }
  }
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// YAML → form parsing
//
// Hydrate the form when the user edits an existing saved YAML. We tolerate
// missing keys, weighted mappings, and a few cosmetic differences (booleans
// encoded as 0/1, choice values as either name or integer). Anything we
// don't understand is silently dropped from the form — the original YAML
// can still be edited by overwriting the option in the form.

function pickGame(parsed: any): GameKey {
  const raw = parsed && typeof parsed === "object" ? parsed.game : null;
  if (raw === "Pokemon Crystal Prerelease") return "Pokemon Crystal Prerelease";
  return "Pokemon Crystal";
}

function coerceSingle(opt: OptionDef, raw: any): SingleValue {
  // Weighted dict — collapse to the highest-weight entry's value.
  if (raw && typeof raw === "object" && !Array.isArray(raw)) {
    // Caller should have handled this; fall through to default.
    return initialValueFor(opt);
  }
  if (opt.kind === "toggle" || opt.kind === "toggle_on") {
    if (raw === true || raw === 1 || raw === "true" || raw === "on" || raw === "yes") return { mode: "single", value: true };
    if (raw === false || raw === 0 || raw === "false" || raw === "off" || raw === "no") return { mode: "single", value: false };
    return initialValueFor(opt);
  }
  if (opt.kind === "choice" && opt.choices) {
    if (typeof raw === "string" && opt.choices.includes(raw)) return { mode: "single", value: raw };
    if (typeof raw === "number" && opt.choices[raw] !== undefined) return { mode: "single", value: opt.choices[raw] };
    return initialValueFor(opt);
  }
  if (opt.kind === "range") {
    if (typeof raw === "number") return { mode: "single", value: raw };
    if (typeof raw === "string" && /^-?\d+$/.test(raw)) return { mode: "single", value: Number(raw) };
    return initialValueFor(opt);
  }
  if (opt.kind === "named_range") {
    if (typeof raw === "number") return { mode: "single", value: raw };
    if (typeof raw === "string") return { mode: "single", value: raw };
    return initialValueFor(opt);
  }
  if (opt.kind === "option_set" || opt.kind === "pokemon_set" || opt.kind === "option_list") {
    if (Array.isArray(raw)) return { mode: "single", value: raw.map(String) };
    return initialValueFor(opt);
  }
  if (opt.kind === "free_text") {
    return { mode: "single", value: raw == null ? "" : String(raw) };
  }
  // option_dict / option_counter / other — re-serialize whatever js-yaml gave us.
  if (raw === undefined || raw === null) return initialValueFor(opt);
  // Empty scalars (`""`, `null`) → treat as "use default" so the textarea
  // stays empty instead of showing literal `''` after a round-trip.
  if (raw === "") return initialValueFor(opt);
  try {
    return { mode: "single", value: yaml.dump(raw, { flowLevel: 0 }).trim() };
  } catch {
    return { mode: "single", value: String(raw) };
  }
}

function coerceWeighted(entries: [unknown, unknown][]): WeightedValue {
  return {
    mode: "weighted",
    entries: entries.map(([k, w]) => ({
      value: k == null ? "" : String(k),
      weight: Number(w) || 0,
    })),
  };
}

export function parseYamlToForm(text: string): FormState {
  let parsed: any = null;
  try {
    parsed = yaml.load(text);
  } catch {
    parsed = null;
  }
  const game = pickGame(parsed);
  const schema = SCHEMAS[game];
  const form: FormState = {
    game,
    name: typeof parsed?.name === "string" ? parsed.name : "Player1",
    description: typeof parsed?.description === "string" ? parsed.description : "",
    values: {},
  };

  const section = parsed && typeof parsed === "object" ? parsed[schema.game] : null;
  if (!section || typeof section !== "object") return form;

  // Option kinds whose YAML value is itself a mapping. For these, an object
  // value means "the option's data", not "weighted randomization".
  const DICT_KINDS = new Set<OptionKind>(["option_dict", "option_counter", "other"]);

  for (const group of schema.groups) {
    for (const opt of group.options) {
      if (!(opt.yaml_key in section)) continue;
      const raw = (section as any)[opt.yaml_key];
      const isMapping = raw && typeof raw === "object" && !Array.isArray(raw);
      if (isMapping && !DICT_KINDS.has(opt.kind)) {
        const entries = Object.entries(raw);
        // Empty mapping {} → treat as default rather than empty weighted.
        if (entries.length === 0) continue;
        form.values[opt.yaml_key] = coerceWeighted(entries);
      } else {
        form.values[opt.yaml_key] = coerceSingle(opt, raw);
      }
    }
  }
  return form;
}

// Default initial form value for an option, mirroring the documented default.
export function initialValueFor(opt: OptionDef): SingleValue {
  const d = opt.default;
  if (opt.kind === "toggle" || opt.kind === "toggle_on") {
    return { mode: "single", value: d === 1 || d === true };
  }
  if (opt.kind === "choice" && opt.choices) {
    const idx = typeof d === "number" ? d : 0;
    return { mode: "single", value: opt.choices[idx] ?? opt.choices[0] ?? "" };
  }
  if (opt.kind === "named_range" || opt.kind === "range") {
    if (typeof d === "number") return { mode: "single", value: d };
    return { mode: "single", value: opt.range_start ?? 0 };
  }
  if (opt.kind === "option_set" || opt.kind === "pokemon_set" || opt.kind === "option_list") {
    return { mode: "single", value: Array.isArray(d) ? (d as string[]) : [] };
  }
  return { mode: "single", value: typeof d === "string" ? d : "" };
}
