// Types + YAML serializer for the YAML creation UI. The schema JSON is
// regenerated by `pack.sh` from the vendored apworlds, so changes to
// upstream options.py are picked up the same way as the world tars.

import * as yaml from "js-yaml";
import rawSchema from "../generated/yaml-schema.json";

// Archipelago reads YAMLs with PyYAML, which follows YAML 1.1: on/off/yes/no
// are booleans, 0x/0 prefixes are hex/octal, and 80E040 (no dot) is text, not
// the float YAML 1.2 makes of it. Read them the same way so the form sees what
// Archipelago will. (dump already quotes for 1.1 and 1.2 alike.)
const LOAD_SCHEMA = yaml.YAML11_SCHEMA;

export type OptionKind =
  | "toggle"
  | "toggle_on"
  | "choice"
  | "range"
  | "named_range"
  | "option_set"
  | "pokemon_set"
  | "option_dict"
  | "option_list"
  | "option_counter"
  | "free_text"
  | "other";

export type OptionDef = {
  name: string;             // Python class name, e.g. "EliteFourCount"
  yaml_key: string;         // dataclass field, e.g. "elite_four_count"
  kind: OptionKind;
  docstring: string;
  display_name: string;
  default: unknown;
  range_start?: number | null;
  range_end?: number | null;
  choices?: string[] | null;                          // "choice"
  choice_values?: (number | null)[] | null;           // parallel to choices
  special_range_names?: Record<string, number | null> | null;  // "named_range"
  valid_keys?: string[] | null;                       // "option_set"/"pokemon_set"
  valid_keys_computed?: boolean;
};

export type OptionGroup = { name: string; options: OptionDef[] };
export type WorldSchema = { game: string; groups: OptionGroup[] };

export type GameKey = "Pokemon Crystal" | "Pokemon Crystal Prerelease";

export const SCHEMAS: Record<GameKey, WorldSchema> = rawSchema as any;

// ---------------------------------------------------------------------------
// Form value model
//
// Each option in the form is either a single scalar value, or a weighted
// table when the user has toggled weights on for that option.
export type SingleValue = {
  mode: "single";
  value: string | number | boolean | string[];
};
export type WeightedValue = {
  mode: "weighted";
  // Each entry maps a serialized value (always a string) to an integer weight.
  // We keep these as parallel arrays rather than an object so the UI can
  // preserve insertion order while editing.
  entries: { value: string; weight: number }[];
};
export type FormValue = SingleValue | WeightedValue;

export type FormState = {
  game: GameKey;
  name: string;
  description: string;
  // yaml_key → FormValue. Options the user never touched are omitted and
  // serialize as the option's documented default.
  values: Record<string, FormValue>;
  // Keys an edited YAML carried that the form has no control for (top-level
  // `requires`/`triggers`, options the schema doesn't know). Emitted back
  // verbatim so an edit round-trip doesn't strip them.
  extraTop?: Record<string, unknown>;
  extraSection?: Record<string, unknown>;
  // Why the YAML this form was parsed from can't round-trip exactly. Saving
  // an edit keeps the original library entry when this is non-empty.
  lossy?: string[];
};

// ---------------------------------------------------------------------------
// YAML serialization
//
// Archipelago YAMLs are intentionally lenient — we don't need a full YAML
// emitter, just predictable output for the option types we drive. Strings
// that need quoting are wrapped in double quotes; everything else is emitted
// as a bare scalar / flow-style list / block mapping.

// Plain only when it can't read as anything but this string: starts with a
// letter or underscore (so no numbers, 0x10, .inf, quotes, indicators), holds
// no YAML syntax, and isn't a YAML 1.1 bool/null (Archipelago loads 1.1).
// Everything else is emitted as a JSON string, which is always a valid YAML
// double-quoted scalar, newlines and control characters included.
const PLAIN_SAFE = /^[A-Za-z_][\w .\-()']*$/;
const RESERVED = /^(true|false|null|yes|no|on|off|y|n)$/i;

function quoteIfNeeded(s: string): string {
  if (PLAIN_SAFE.test(s) && !RESERVED.test(s) && !/\s$/.test(s)) return s;
  return JSON.stringify(s);
}

function emitScalar(v: unknown): string {
  if (v === true) return "true";
  if (v === false) return "false";
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  return quoteIfNeeded(String(v));
}

function emitFlowList(items: unknown[]): string {
  return "[" + items.map(emitScalar).join(", ") + "]";
}

function emitWeighted(entries: { value: string; weight: number }[]): string {
  // Inline mapping: { v1: w1, v2: w2 }. Rows naming the same value merge
  // (a duplicate key would keep only the last weight, and js-yaml rejects
  // it); blank rows are skipped (`"": 50` fails generation).
  // Integer keys go out as integers: a choice weighted by value ({0: 50})
  // needs them unquoted, and ranges read either form. They merge by that
  // number, so 5 and 05 can't come out as the same key twice.
  const merged = new Map<string | number, number>();
  for (const e of entries) {
    if (e.value.trim() === "") continue;
    const key = /^-?\d+$/.test(e.value) ? Number(e.value) : e.value;
    merged.set(key, (merged.get(key) ?? 0) + (e.weight | 0));
  }
  const parts = [...merged].map(([v, w]) => `${emitScalar(v)}: ${w}`);
  return "{" + parts.join(", ") + "}";
}

function defaultLiteral(opt: OptionDef): string {
  // For options the user never touched, emit a representation that matches
  // the option's documented default.
  const d = opt.default;
  if (opt.kind === "toggle" || opt.kind === "toggle_on") {
    // AP's YAML uses 0/1 weights here, but a bare scalar works too.
    return emitScalar(d === 1 || d === true);
  }
  if ((opt.kind === "choice" || isTextChoice(opt)) && opt.choices && opt.choices.length) {
    // Choice options inherit AP's `default = 0` from NumericOption when they
    // don't declare one explicitly, so the schema may record `default: null`
    // (e.g. LockKantoGyms). Fall back to the first choice rather than emitting
    // an empty string, which fails generation with `Could not find option ""`.
    return emitScalar((typeof d === "number" ? choiceForValue(opt, d) : null) ?? opt.choices[0]);
  }
  if (opt.kind === "named_range" && opt.special_range_names) {
    for (const [name, val] of Object.entries(opt.special_range_names)) {
      if (val !== null && val === d) return emitScalar(name);
    }
    if (typeof d === "number") return emitScalar(d);
  }
  if (opt.kind === "range" && typeof d === "number") return emitScalar(d);
  if (Array.isArray(d)) return emitFlowList(d);
  if (d && typeof d === "object") {
    // option_dict / option_counter / etc. — emit as a flow-style mapping.
    try {
      return yaml.dump(d, { flowLevel: 0, lineWidth: -1 }).trim();
    } catch {
      return "{}";
    }
  }
  if (d === null || d === undefined) {
    // Sensible per-kind fallbacks.
    if (opt.kind === "range" && typeof opt.range_start === "number") return emitScalar(opt.range_start);
    if (opt.kind === "option_set" || opt.kind === "pokemon_set" || opt.kind === "option_list") return emitFlowList([]);
    // option_dict / option_counter / other — these are typically mapping-shaped
    // upstream (e.g. `start_inventory_from_pool` is an OptionDict). Emit an
    // empty mapping rather than a quoted empty string, which round-trips
    // through js-yaml without sprouting literal `''`.
    if (opt.kind === "option_dict" || opt.kind === "option_counter" || opt.kind === "other") return "{}";
    return '""';
  }
  return emitScalar(d);
}

function emitFormValue(opt: OptionDef, val: FormValue): string {
  if (val.mode === "weighted") return emitWeighted(val.entries);
  const v = val.value;
  if (opt.kind === "option_set" || opt.kind === "pokemon_set" || opt.kind === "option_list") {
    return emitFlowList(Array.isArray(v) ? v : []);
  }
  if (opt.kind === "toggle" || opt.kind === "toggle_on") return emitScalar(!!v);
  if (isTextChoice(opt)) {
    // Never re-parsed as YAML: js-yaml (1.2) would read colour 80E040 as
    // 8e41 and 008040 as 8040. A choice named or numbered goes out as its
    // name; anything else is text, quoted whenever it could read as a number.
    const text = typeof v === "string" ? v.trim() : String(v ?? "");
    if (!text) return defaultLiteral(opt);
    const named = opt.choices!.find((c) => c.toLowerCase() === text.toLowerCase())
      ?? (/^(0|-?[1-9]\d*)$/.test(text) ? choiceForValue(opt, Number(text)) : null);  // 000001 is a colour
    return emitScalar(named ?? text);
  }
  if (opt.kind === "option_dict" || opt.kind === "option_counter" || opt.kind === "other") {
    // The textarea holds inline YAML. Re-parse → re-emit as flow style so
    // it sits on one line next to the option key (no awkward block-style
    // indentation drift inside the rest of the document).
    const text = typeof v === "string" ? v.trim() : "";
    if (!text) return "{}";
    try {
      const parsed = yaml.load(text, { schema: LOAD_SCHEMA });
      if (parsed && typeof parsed === "object") {
        return yaml.dump(parsed, { flowLevel: 0, lineWidth: -1 }).trim();
      }
      // A scalar keeps its type: "other" covers TextChoice options
      // (trainer_palette), where 0 picks a choice but "0" is custom text.
      if (parsed !== undefined) return emitScalar(parsed);
    } catch { /* fall through */ }
    return emitScalar(text);
  }
  return emitScalar(v);
}

function emitFlow(v: unknown): string {
  try { return yaml.dump(v, { flowLevel: 0, lineWidth: -1 }).trim(); }
  catch { return "null"; }
}

// Block-style dump of a mapping, indented to sit under `indent`.
function emitExtra(obj: Record<string, unknown>, indent: string): string[] {
  let text: string;
  try { text = yaml.dump(obj, { lineWidth: -1 }); }
  catch { return []; }
  return text.trimEnd().split("\n").map(l => indent + l);
}

const HEADER_TEMPLATE = `# Generated by Crystal AP Web — edit by hand if you want anything fancier.
# Docs: https://archipelago.gg/tutorial/Archipelago/setup/en
`;

export function serializeFormToYaml(form: FormState): string {
  const schema = SCHEMAS[form.game];
  const lines: string[] = [];
  lines.push(HEADER_TEMPLATE.trimEnd());
  lines.push("");
  lines.push(`name: ${emitScalar(form.name || "Player1")}`);
  if (form.description.trim()) lines.push(`description: ${emitScalar(form.description.trim())}`);
  lines.push(`game: ${emitScalar(schema.game)}`);
  lines.push("");
  lines.push(`${emitScalar(schema.game)}:`);

  // A carried-over key this schema does know (the form switched version)
  // fills in for that option's default rather than being emitted twice.
  const extraSection = { ...form.extraSection };
  for (const group of schema.groups) {
    lines.push("");
    lines.push(`  # --- ${group.name} ---`);
    for (const opt of group.options) {
      const user = form.values[opt.yaml_key];
      let rendered: string;
      if (user) rendered = emitFormValue(opt, user);
      else if (opt.yaml_key in extraSection) rendered = emitFlow(extraSection[opt.yaml_key]);
      else rendered = defaultLiteral(opt);
      delete extraSection[opt.yaml_key];
      lines.push(`  ${opt.yaml_key}: ${rendered}`);
    }
  }
  if (Object.keys(extraSection).length) {
    lines.push("");
    lines.push("  # --- other options ---");
    lines.push(...emitExtra(extraSection, "  "));
  }
  // After a version switch the original's section for the now-current game
  // can sit in extraTop; the form's section above replaces it.
  const extraTop = { ...form.extraTop };
  delete extraTop[schema.game];
  if (Object.keys(extraTop).length) {
    lines.push("");
    lines.push(...emitExtra(extraTop, ""));
  }
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// YAML → form parsing
//
// Hydrate the form when the user edits an existing saved YAML. We tolerate
// missing keys, weighted mappings, and a few cosmetic differences (booleans
// encoded as 0/1, choice values as either name or integer). Keys the form
// has no control for ride along in extraTop/extraSection, and scalar values
// it can't show (`random`, `random-range-…`) become a one-row weighted table,
// which Archipelago reads the same way. Anything still unrepresentable is
// listed in `lossy`.

function pickGame(parsed: any): GameKey {
  const raw = parsed && typeof parsed === "object" ? parsed.game : null;
  if (raw === "Pokemon Crystal Prerelease") return "Pokemon Crystal Prerelease";
  return "Pokemon Crystal";
}

// Option kinds whose YAML value is itself a mapping. For these, an object
// value means "the option's data", not "weighted randomization".
const DICT_KINDS = new Set<OptionKind>(["option_dict", "option_counter", "other"]);

// null when the value isn't one the option's control can show.
function coerceSingle(opt: OptionDef, raw: any): SingleValue | null {
  if (raw && typeof raw === "object" && !Array.isArray(raw) && !DICT_KINDS.has(opt.kind)) {
    // Weighted mapping for a scalar option — the caller handles those, so
    // reaching here means the value is malformed.
    return null;
  }
  if (opt.kind === "toggle" || opt.kind === "toggle_on") {
    if (raw === true || raw === 1 || raw === "true" || raw === "on" || raw === "yes") return { mode: "single", value: true };
    if (raw === false || raw === 0 || raw === "false" || raw === "off" || raw === "no") return { mode: "single", value: false };
    return null;
  }
  if (opt.kind === "choice" && opt.choices) {
    if (typeof raw === "string" && opt.choices.includes(raw)) return { mode: "single", value: raw };
    if (typeof raw === "number") {
      const name = choiceForValue(opt, raw);
      if (name) return { mode: "single", value: name };
    }
    return null;
  }
  if (opt.kind === "range") {
    if (typeof raw === "number") return { mode: "single", value: raw };
    if (typeof raw === "string" && /^-?\d+$/.test(raw)) return { mode: "single", value: Number(raw) };
    return null;
  }
  if (opt.kind === "named_range") {
    // Only what the editor can show: a number, or one of the option's special
    // names (matched as NamedRange.from_text does, case-insensitively).
    // `random-…` and unknown names fall to the caller's verbatim weighted row.
    const n = typeof raw === "number" ? raw
      : typeof raw === "string" && /^-?\d+$/.test(raw) ? Number(raw) : null;
    if (n !== null) return { mode: "single", value: specialNameFor(opt, n) ?? n };
    if (typeof raw === "string") {
      const name = Object.keys(opt.special_range_names ?? {}).find((k) => k.toLowerCase() === raw.toLowerCase());
      if (name) return { mode: "single", value: name };
    }
    return null;
  }
  if (opt.kind === "option_set" || opt.kind === "pokemon_set" || opt.kind === "option_list") {
    if (Array.isArray(raw)) return { mode: "single", value: raw.map(String) };
    return null;
  }
  if (opt.kind === "free_text") {
    return { mode: "single", value: raw == null ? "" : String(raw) };
  }
  if (isTextChoice(opt)) {
    if (raw == null || raw === "") return initialValueFor(opt);
    if (typeof raw === "string") return { mode: "single", value: raw };
    // A number is a choice value; any other number is text js-yaml already
    // misread (an unquoted colour like 80E040), which can't be recovered.
    const name = typeof raw === "number" ? choiceForValue(opt, raw) : null;
    return name ? { mode: "single", value: name } : null;
  }
  // option_dict / option_counter / other — re-serialize whatever js-yaml gave us.
  if (raw === undefined || raw === null) return initialValueFor(opt);
  // Empty scalars (`""`, `null`) and empty mappings (`{}`) → treat as "use
  // default" so the textarea stays empty instead of showing literal `''` or
  // `{}` after a round-trip.
  if (raw === "") return initialValueFor(opt);
  if (typeof raw === "object" && !Array.isArray(raw) && Object.keys(raw).length === 0) {
    return initialValueFor(opt);
  }
  try {
    return { mode: "single", value: yaml.dump(raw, { flowLevel: 0 }).trim() };
  } catch {
    return { mode: "single", value: String(raw) };
  }
}

function coerceWeighted(entries: [unknown, unknown][]): WeightedValue {
  return {
    mode: "weighted",
    entries: entries.map(([k, w]) => ({
      value: k == null ? "" : String(k),
      weight: Number(w) || 0,
    })),
  };
}

// A top-level text field as the form holds it. Numbers read as their text
// (name: 1234 is the name "1234"); anything else (a weighted name) can't be
// shown and is recorded as lossy.
function textField(v: unknown, key: string, lossy: string[]): string | null {
  if (v == null) return null;
  if (typeof v === "string") return v;
  if (typeof v === "number") return String(v);
  lossy.push(`its \`${key}:\``);
  return null;
}

const COLLECTION_KINDS = new Set<OptionKind>(["option_set", "pokemon_set", "option_list", "option_dict", "option_counter", "other"]);

export function parseYamlToForm(text: string): FormState {
  let parsed: any = null;
  const lossy: string[] = [];
  try {
    // json: duplicate keys keep the last value instead of throwing, so such a
    // YAML still opens for fixing (Archipelago's own loader rejects it).
    // An empty document throws in js-yaml 5; it's just an empty YAML.
    parsed = text.trim() ? yaml.load(text, { json: true, schema: LOAD_SCHEMA }) : null;
  } catch {
    lossy.push("the YAML doesn't parse");
  }
  if (parsed != null && (typeof parsed !== "object" || Array.isArray(parsed))) {
    lossy.push("the YAML isn't a mapping");
    parsed = null;
  }
  if (parsed && parsed.game != null && typeof parsed.game !== "string") {
    lossy.push("its weighted `game:`");
  }
  const game = pickGame(parsed);
  const schema = SCHEMAS[game];
  const form: FormState = {
    game,
    name: textField(parsed?.name, "name", lossy) ?? "Player1",
    description: textField(parsed?.description, "description", lossy) ?? "",
    values: {},
    lossy,
  };
  if (!parsed) return form;

  const extraTop: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(parsed)) {
    if (k === "name" || k === "description" || k === "game" || k === schema.game) continue;
    extraTop[k] = v;
  }
  if (Object.keys(extraTop).length) form.extraTop = extraTop;

  const section = parsed[schema.game];
  if (!section || typeof section !== "object" || Array.isArray(section)) return form;

  const known = new Set<string>();
  for (const group of schema.groups) {
    for (const opt of group.options) {
      known.add(opt.yaml_key);
      if (!(opt.yaml_key in section)) continue;
      const raw = (section as any)[opt.yaml_key];
      const isMapping = raw && typeof raw === "object" && !Array.isArray(raw);
      if (isMapping && !DICT_KINDS.has(opt.kind)) {
        const entries = Object.entries(raw);
        // Empty mapping {} → treat as default rather than empty weighted.
        if (entries.length === 0) continue;
        form.values[opt.yaml_key] = coerceWeighted(entries);
        continue;
      }
      const single = coerceSingle(opt, raw);
      if (single) form.values[opt.yaml_key] = single;
      else if (!COLLECTION_KINDS.has(opt.kind) && raw != null && typeof raw !== "object") {
        // `random`, `random-high`, an out-of-list choice: keep it verbatim.
        form.values[opt.yaml_key] = coerceWeighted([[raw, 1]]);
      } else {
        lossy.push(`the value of ${opt.yaml_key}`);
      }
    }
  }
  const extraSection: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(section)) if (!known.has(k)) extraSection[k] = v;
  if (Object.keys(extraSection).length) form.extraSection = extraSection;
  return form;
}

// The choice named by numeric value `n` (a YAML can give a choice by value,
// and defaults are values). Values aren't always positions: SharedPrimaryType
// skips from rock = 6 to bug = 8. Schemas without values fall back to position.
export function choiceForValue(opt: OptionDef, n: number): string | null {
  if (!opt.choices) return null;
  const idx = opt.choice_values ? opt.choice_values.indexOf(n) : n;
  return opt.choices[idx] ?? null;
}

// A TextChoice (trainer_palette): named choices, or any text (a hex colour).
// The schema files it as "other" with choices attached.
export function isTextChoice(opt: OptionDef): boolean {
  return opt.kind === "other" && !!opt.choices?.length;
}

// The special name a named range gives `n`, if any.
export function specialNameFor(opt: OptionDef, n: number): string | null {
  if (opt.kind !== "named_range") return null;
  for (const [name, v] of Object.entries(opt.special_range_names ?? {})) if (v === n) return name;
  return null;
}

// Default initial form value for an option, mirroring the documented default.
export function initialValueFor(opt: OptionDef): SingleValue {
  const d = opt.default;
  if (opt.kind === "toggle" || opt.kind === "toggle_on") {
    return { mode: "single", value: d === 1 || d === true };
  }
  if ((opt.kind === "choice" || isTextChoice(opt)) && opt.choices) {
    return { mode: "single", value: (typeof d === "number" ? choiceForValue(opt, d) : null) ?? opt.choices[0] ?? "" };
  }
  if (opt.kind === "named_range" || opt.kind === "range") {
    // A named range's default is often a special value, even one below
    // range_start (vanilla = -1): start on its name, which the editor shows.
    if (typeof d === "number") return { mode: "single", value: specialNameFor(opt, d) ?? d };
    return { mode: "single", value: opt.range_start ?? 0 };
  }
  if (opt.kind === "option_set" || opt.kind === "pokemon_set" || opt.kind === "option_list") {
    return { mode: "single", value: Array.isArray(d) ? (d as string[]) : [] };
  }
  return { mode: "single", value: typeof d === "string" ? d : "" };
}
